# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ordernum', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('qtype', models.CharField(choices=[('RB', 'Один из ...'), ('CB', 'Несколько из ...'), ('LL', 'Путанка')], default='RB', max_length=2)),
            ],
            options={
                'verbose_name': 'Простой Ответ',
                'verbose_name_plural': 'Простые Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='полное описание')),
                ('public', models.BooleanField(default=False, verbose_name='публичное')),
                ('qtype', models.CharField(choices=[('RB', 'Один из ...'), ('CB', 'Несколько из ...'), ('LL', 'Путанка')], default='RB', max_length=2, verbose_name='Тип вопроса')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division', verbose_name='организация')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='AnswerCB',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
            ],
            options={
                'verbose_name': 'Множественный Ответ (CheckBox)',
                'verbose_name_plural': 'Множественные Ответы (CheckBox)',
            },
            bases=('questions.answer',),
        ),
        migrations.CreateModel(
            name='AnswerLL',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
                ('linkeditem', models.TextField()),
                ('ordernumitem', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ответ-Путанка',
                'verbose_name_plural': 'Ответы-Путанки',
            },
            bases=('questions.answer',),
        ),
        migrations.CreateModel(
            name='AnswerRB',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
            ],
            options={
                'verbose_name': 'Одиночный Ответ (RadioButton)',
                'verbose_name_plural': 'Одиночные Ответы (RadioButton)',
            },
            bases=('questions.answer',),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question'),
        ),
    ]
