# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ordernum', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Простые Ответы',
                'verbose_name': 'Простой Ответ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('RB', 'Один из ...'), ('CB', 'Несколько из ...'), ('LL', 'Путанка')], default='RB', max_length=2)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='AnswerCB',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
            ],
            options={
                'verbose_name_plural': 'Множественные Ответы (CheckBox)',
                'verbose_name': 'Множественный Ответ (CheckBox)',
            },
            bases=('questions.answer',),
        ),
        migrations.CreateModel(
            name='AnswerLL',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
                ('linkeditem', models.TextField()),
                ('ordernumitem', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ответы-Путанки',
                'verbose_name': 'Ответ-Путанка',
            },
            bases=('questions.answer',),
        ),
        migrations.CreateModel(
            name='AnswerRB',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
            ],
            options={
                'verbose_name_plural': 'Одиночные Ответы (RadioButton)',
                'verbose_name': 'Одиночный Ответ (RadioButton)',
            },
            bases=('questions.answer',),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
