# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='qtype',
            field=models.CharField(choices=[('RB', 'Один из ...'), ('CB', 'Несколько из ...'), ('LL', 'Путанка')], default='RB', max_length=2, null=True),
        ),
    ]
