# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170715_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('ordernum1', models.PositiveIntegerField(blank=True, null=True)),
                ('ordernum2', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
            options={
                'verbose_name': 'Ответ-Путанка',
                'verbose_name_plural': 'Ответы-Путанки',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Простой Ответ', 'verbose_name_plural': 'Простые Ответы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='ordernum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
