# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170717_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCB',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
            ],
            options={
                'verbose_name': 'Множественный Ответ (CheckBox)',
                'verbose_name_plural': 'Множественные Ответы (CheckBox)',
            },
            bases=('questions.answer',),
        ),
        migrations.CreateModel(
            name='AnswerRB',
            fields=[
                ('answer_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer')),
            ],
            options={
                'verbose_name': 'Одиночный Ответ (RadioButton)',
                'verbose_name_plural': 'Одиночные Ответы (RadioButton)',
            },
            bases=('questions.answer',),
        ),
        migrations.RenameField(
            model_name='answerll',
            old_name='content1',
            new_name='linkeditem',
        ),
        migrations.RenameField(
            model_name='answerll',
            old_name='ordernum1',
            new_name='ordernumitem',
        ),
        migrations.RemoveField(
            model_name='answerll',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='answerll',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answerll',
            name='ordernum2',
        ),
        migrations.RemoveField(
            model_name='answerll',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answerll',
            name='score',
        ),
        migrations.AddField(
            model_name='answerll',
            name='answer_ptr',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Answer'),
            preserve_default=False,
        ),
    ]
