# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170813_1559'),
        ('questions', '0005_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Division'),
        ),
    ]
