# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20170813_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
