# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20170825_1745'),
        ('questions', '0008_question_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='clients.Person'),
            preserve_default=False,
        ),
    ]
