# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division', verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=60, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='question',
            name='public',
            field=models.BooleanField(default=False, verbose_name='публиное'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('RB', 'Один из ...'), ('CB', 'Несколько из ...'), ('LL', 'Путанка')], default='RB', max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
