# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Состав Опросного листа',
                'verbose_name': 'Состав Опросного листа',
            },
        ),
        migrations.CreateModel(
            name='QueryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Опросные листы',
                'verbose_name': 'Опросный лист',
            },
        ),
        migrations.AddField(
            model_name='querycontent',
            name='querylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querylists.QueryList'),
        ),
        migrations.AddField(
            model_name='querycontent',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='querycontent',
            unique_together=set([('querylist', 'question')]),
        ),
    ]
