# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Наполнение опросника',
                'verbose_name_plural': 'Наполнение опросников',
            },
        ),
        migrations.CreateModel(
            name='QueryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
            },
        ),
        migrations.AddField(
            model_name='querycontent',
            name='querylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='querylists.QueryList'),
        ),
        migrations.AddField(
            model_name='querycontent',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='querycontent',
            unique_together=set([('querylist', 'question')]),
        ),
    ]
