# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querylists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querycontent',
            options={'verbose_name': 'Состав Анкеты', 'verbose_name_plural': 'Состав Анкет'},
        ),
        migrations.AlterModelOptions(
            name='querylist',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
    ]
