# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querylists', '0002_auto_20170729_1625'),
        ('querylists', '0002_auto_20170730_1057'),
    ]

    operations = [
    ]
