# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querylists', '0003_merge_20170806_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querycontent',
            name='querylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='querylists.QueryList'),
        ),
        migrations.AlterField(
            model_name='querycontent',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question'),
        ),
    ]
