# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querylists', '0004_auto_20170806_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylist',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
