# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querylists', '0007_auto_20170813_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querycontent',
            options={'verbose_name': 'Наполнение опросника', 'verbose_name_plural': 'Наполнение опросников'},
        ),
        migrations.AlterModelOptions(
            name='querylist',
            options={'verbose_name': 'Опросник', 'verbose_name_plural': 'Опросники'},
        ),
        migrations.AlterField(
            model_name='querylist',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
