# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('querylists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Попытка пройти тест',
                'verbose_name_plural': 'Попытки пройти тест',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец')),
                ('squads', models.ManyToManyField(blank=True, to='clients.Squad', verbose_name='назначение')),
            ],
            options={
                'verbose_name': 'Назначеное тестирование',
                'verbose_name_plural': 'Расписание заданий',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('viewable', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('autoclose', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=60)),
                ('public', models.BooleanField(default=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец')),
                ('querylist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='querylists.QueryList')),
            ],
            options={
                'verbose_name': 'Задание на тестирование',
                'verbose_name_plural': 'Задания на тестирование',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Task'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Schedule'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
