# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
