# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20170722_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestCase'),
        ),
    ]
