# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20170722_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Назначеное тестирование', 'verbose_name_plural': 'Расписание заданий'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание на тестирование', 'verbose_name_plural': 'Задания на тестирование'},
        ),
    ]
