# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20170813_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
