# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_auto_20170828_1816'),
        ('schedules', '0014_auto_20170825_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.Person', verbose_name='владелец'),
            preserve_default=False,
        ),
    ]
