# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('shortname', models.CharField(max_length=30, verbose_name='абревиатура')),
                ('corporate', models.BooleanField(default=False, verbose_name='корпорация')),
                ('public', models.BooleanField(default=True, verbose_name='публичный контент')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('applabel', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('shortname', models.CharField(max_length=15, verbose_name='абревиатура')),
                ('public', models.BooleanField(default=False, verbose_name='публичный контент')),
                ('private', models.BooleanField(default=False, verbose_name='контент только этого подразделения')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=30, verbose_name='aka')),
                ('used', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division', verbose_name='входит в организацию')),
            ],
            options={
                'verbose_name': 'личность',
                'verbose_name_plural': 'личности',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('shortname', models.CharField(max_length=30, unique=True, verbose_name='абревиатура')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl', models.CharField(max_length=10)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.DataType')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('shortname', models.CharField(max_length=30, verbose_name='абревиатура')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Division', verbose_name='организация')),
                ('members', models.ManyToManyField(to='clients.Person', verbose_name='участники')),
            ],
            options={
                'verbose_name': 'рабочая группа',
                'verbose_name_plural': 'рабочие группы',
            },
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('client_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('fullname', models.CharField(max_length=120, verbose_name='полное наименование')),
                ('address', models.TextField(blank=True, null=True, verbose_name='почтовый адрес')),
            ],
            options={
                'verbose_name': 'дополнительная информация о Клиенте',
                'verbose_name_plural': 'дополнительная информация о Клиентах',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='acls',
            field=models.ManyToManyField(through='clients.RolePermission', to='clients.DataType'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, to='clients.Role', verbose_name='роли'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set([('applabel', 'model')]),
        ),
        migrations.AlterUniqueTogether(
            name='squad',
            unique_together=set([('shortname', 'division')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set([('role', 'datatype')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('user', 'shortname')]),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('client', 'name'), ('client', 'shortname')]),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='rootdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division', verbose_name='корневая организация'),
        ),
    ]
