# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=15)),
                ('public', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('client', 'name'), ('client', 'shortname')]),
        ),
    ]
