# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170813_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
