# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170813_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='corporate',
            field=models.BooleanField(default=False, verbose_name='Корпорация'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shortname',
            field=models.CharField(max_length=15, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='division',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Корпоративное управление'),
        ),
        migrations.AlterField(
            model_name='division',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Публичный контент'),
        ),
        migrations.AlterField(
            model_name='division',
            name='shortname',
            field=models.CharField(max_length=15, verbose_name='Аббревиатура'),
        ),
    ]
