# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20170815_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публичный контент'),
        ),
        migrations.AlterField(
            model_name='division',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Контент только этого подразделения'),
        ),
    ]
