# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20170816_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, verbose_name='полное наименование')),
                ('address', models.TextField(verbose_name='почтовый адрес')),
            ],
        ),
    ]
