# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='почтовый адрес'),
        ),
    ]
