# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20170817_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Личность', 'verbose_name_plural': 'Личности'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='client',
        ),
        migrations.RemoveField(
            model_name='person',
            name='division',
        ),
        migrations.AddField(
            model_name='person',
            name='shortname',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
