# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20170817_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientdata',
            options={'verbose_name': 'дополнительная информация о Клиенте', 'verbose_name_plural': 'дополнительная информация о Клиентах'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'личность', 'verbose_name_plural': 'личности'},
        ),
        migrations.AlterField(
            model_name='client',
            name='corporate',
            field=models.BooleanField(default=False, verbose_name='корпорация'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='public',
            field=models.BooleanField(default=True, verbose_name='публичный контент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shortname',
            field=models.CharField(max_length=15, verbose_name='абревиатура'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=60, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='division',
            name='private',
            field=models.BooleanField(default=False, verbose_name='контент только этого подразделения'),
        ),
        migrations.AlterField(
            model_name='division',
            name='public',
            field=models.BooleanField(default=False, verbose_name='публичный контент'),
        ),
        migrations.AlterField(
            model_name='division',
            name='shortname',
            field=models.CharField(max_length=15, verbose_name='абревиатура'),
        ),
    ]
