# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20170817_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('shortname', models.CharField(max_length=15, verbose_name='абревиатура')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Division', verbose_name='организация')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Person', verbose_name='менеджер группы')),
            ],
            options={
                'verbose_name': 'рабочая группа',
                'verbose_name_plural': 'рабочие группы',
            },
        ),
    ]
