# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_squad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='manager',
        ),
        # migrations.AddField(
        #     model_name='person',
        #     name='clients',
        #     field=models.ManyToManyField(to='clients.Client', verbose_name='от клиента'),
        # ),
        # migrations.AddField(
        #     model_name='person',
        #     name='divisions',
        #     field=models.ManyToManyField(to='clients.Division', verbose_name='входит в организацию'),
        # ),
        # migrations.AddField(
        #     model_name='person',
        #     name='roles',
        #     field=models.ManyToManyField(to='clients.Role', verbose_name='доступная роль'),
        # ),
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(to='clients.Person', verbose_name='участники'),
        ),
    ]
