# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20170817_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='squad',
            unique_together=set([('shortname', 'division')]),
        ),
    ]
