# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20170817_1719'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='person',
        #     name='clients',
        # ),
        # migrations.RemoveField(
        #     model_name='person',
        #     name='divisions',
        # ),
        # migrations.RemoveField(
        #     model_name='person',
        #     name='roles',
        # ),
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AddField(
            model_name='person',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='clients.Division', verbose_name='входит в организацию'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='clients.Role', verbose_name='доступная роль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
