# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20170825_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('applabel', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl', models.CharField(max_length=10)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.DataType')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='acls',
            field=models.ManyToManyField(through='clients.RolePermision', to='clients.DataType'),
        ),
    ]
