# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20170825_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermision',
            unique_together=set([('role', 'datatype')]),
        ),
    ]
