# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20170825_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='название'),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set([('applabel', 'model')]),
        ),
    ]
