# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20170825_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=60, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shortname',
            field=models.CharField(max_length=30, verbose_name='абревиатура'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shortname',
            field=models.CharField(max_length=30, verbose_name='aka'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='shortname',
            field=models.CharField(max_length=30, unique=True, verbose_name='абревиатура'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=60, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='shortname',
            field=models.CharField(max_length=30, verbose_name='абревиатура'),
        ),
    ]
