# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_auto_20170825_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='client_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='rootdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Division', verbose_name='корневая организация'),
        ),
    ]
