# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20170826_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
