# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_remove_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Role', verbose_name='роли'),
        ),
    ]
