# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_person_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, to='clients.Role', verbose_name='роли'),
        ),
    ]
