# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0004_auto_20170717_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тест-кейс',
                'verbose_name_plural': 'Тест-кейсы',
            },
        ),
        migrations.CreateModel(
            name='TestContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestCase')),
            ],
            options={
                'verbose_name': 'Состав Тест-кейса',
                'verbose_name_plural': 'Состав Тест-кейса',
            },
        ),
        migrations.AlterUniqueTogether(
            name='testcontent',
            unique_together=set([('testcase', 'question')]),
        ),
    ]
