# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
