# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0005_auto_20170722_1715'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField()),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timemark', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='results',
            unique_together=set([('attempt', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set([('schedule', 'attempt')]),
        ),
    ]
