# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ordernum', models.PositiveIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultLL',
            fields=[
                ('result_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Result')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.AnswerLL')),
            ],
            bases=('surveys.result',),
        ),
        migrations.AddField(
            model_name='result',
            name='anketa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Anketa'),
        ),
        migrations.AddField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Answer'),
        ),
    ]
