# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Попытка пройти тест', 'verbose_name_plural': 'Попытки пройти тест'},
        ),
    ]
