# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170806_1853'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLL',
            fields=[
                ('result_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Result')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.AnswerLL')),
            ],
            bases=('surveys.result',),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Attempt'),
        ),
        migrations.AlterField(
            model_name='result',
            name='anketa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Anketa'),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Answer'),
        ),
    ]
