# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170722_1715'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
            ],
            options={
                'verbose_name_plural': 'Результаты',
                'verbose_name': 'Результат',
            },
        ),
        migrations.AlterUniqueTogether(
            name='results',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='results',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='results',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='results',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Попытка сдать тест-кейс', 'verbose_name_plural': 'Попытки сдать тест-кейс'},
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AddField(
            model_name='result',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Attempt'),
        ),
        migrations.AddField(
            model_name='result',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('attempt', 'question')]),
        ),
    ]
