# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20170730_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
