# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20170723_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
