# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170722_1715'),
        ('surveys', '0003_auto_20170723_1146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('attempt', 'question', 'answer')]),
        ),
    ]
