# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170722_1715'),
        ('surveys', '0004_auto_20170723_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCB',
            fields=[
                ('result_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Result')),
                ('answerCB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AnswerCB')),
            ],
            options={
                'verbose_name_plural': 'Множественные Ответы (CheckBox)',
                'verbose_name': 'Множественный Ответ (CheckBox)',
            },
            bases=('surveys.result',),
        ),
        migrations.CreateModel(
            name='ResultLL',
            fields=[
                ('result_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Result')),
                ('answerLL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AnswerLL')),
            ],
            options={
                'verbose_name_plural': 'Ответы-Путанки',
                'verbose_name': 'Ответ-Путанка',
            },
            bases=('surveys.result',),
        ),
        migrations.CreateModel(
            name='ResultRB',
            fields=[
                ('result_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Result')),
                ('answerRB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AnswerRB')),
            ],
            options={
                'verbose_name_plural': 'Одиночные Ответы (RadioButton)',
                'verbose_name': 'Одиночный Ответ (RadioButton)',
            },
            bases=('surveys.result',),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='result',
            name='answer',
        ),
    ]
