# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170722_1715'),
        ('surveys', '0005_auto_20170723_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultll',
            name='itemLL',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.AnswerLL'),
            preserve_default=False,
        ),
    ]
